<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

$relationships = array (
  'gi_products_modified_user' => 
  array (
    'id' => '1fd00d3e-533f-1894-92df-55d560ea6a73',
    'relationship_name' => 'gi_products_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'GI_Products',
    'rhs_table' => 'gi_products',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'gi_products_created_by' => 
  array (
    'id' => '1ffaac6e-0d93-a86a-cabb-55d560efc685',
    'relationship_name' => 'gi_products_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'GI_Products',
    'rhs_table' => 'gi_products',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'gi_products_assigned_user' => 
  array (
    'id' => '202604e3-3db5-3945-7011-55d5601c531a',
    'relationship_name' => 'gi_products_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'GI_Products',
    'rhs_table' => 'gi_products',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'accounts_gi_products_1' => 
  array (
    'id' => '5fba5a18-c7ab-9437-0f3a-55d560aa089d',
    'relationship_name' => 'accounts_gi_products_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'GI_Products',
    'rhs_table' => 'gi_products',
    'rhs_key' => 'id',
    'join_table' => 'accounts_gi_products_1_c',
    'join_key_lhs' => 'accounts_gi_products_1accounts_ida',
    'join_key_rhs' => 'accounts_gi_products_1gi_products_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'gi_forecastings_gi_products_1' => 
  array (
    'id' => '61b1e111-1fd5-ba8f-540b-55d56055c7cf',
    'relationship_name' => 'gi_forecastings_gi_products_1',
    'lhs_module' => 'GI_Forecastings',
    'lhs_table' => 'gi_forecastings',
    'lhs_key' => 'id',
    'rhs_module' => 'GI_Products',
    'rhs_table' => 'gi_products',
    'rhs_key' => 'id',
    'join_table' => 'gi_forecastings_gi_products_1_c',
    'join_key_lhs' => 'gi_forecastings_gi_products_1gi_forecastings_ida',
    'join_key_rhs' => 'gi_forecastings_gi_products_1gi_products_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'gi_line_items_change_requests_gi_products_2' => 
  array (
    'id' => '62b714d9-454b-facd-f3b2-55d560ebe3c3',
    'relationship_name' => 'gi_line_items_change_requests_gi_products_2',
    'lhs_module' => 'GI_Line_Items_Change_Requests',
    'lhs_table' => 'gi_line_items_change_requests',
    'lhs_key' => 'id',
    'rhs_module' => 'GI_Products',
    'rhs_table' => 'gi_products',
    'rhs_key' => 'id',
    'join_table' => 'gi_line_items_change_requests_gi_products_2_c',
    'join_key_lhs' => 'gi_line_it60abequests_ida',
    'join_key_rhs' => 'gi_line_items_change_requests_gi_products_2gi_products_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'gi_terms_gi_products_1' => 
  array (
    'id' => '6315fb2b-59f3-21bf-80cb-55d560def8cc',
    'relationship_name' => 'gi_terms_gi_products_1',
    'lhs_module' => 'GI_Terms',
    'lhs_table' => 'gi_terms',
    'lhs_key' => 'id',
    'rhs_module' => 'GI_Products',
    'rhs_table' => 'gi_products',
    'rhs_key' => 'id',
    'join_table' => 'gi_terms_gi_products_1_c',
    'join_key_lhs' => 'gi_terms_gi_products_1gi_terms_ida',
    'join_key_rhs' => 'gi_terms_gi_products_1gi_products_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'gi_products_gi_line_items_1' => 
  array (
    'id' => '63d778ae-1a73-5402-a974-55d56038df8a',
    'relationship_name' => 'gi_products_gi_line_items_1',
    'lhs_module' => 'GI_Products',
    'lhs_table' => 'gi_products',
    'lhs_key' => 'id',
    'rhs_module' => 'GI_Line_Items',
    'rhs_table' => 'gi_line_items',
    'rhs_key' => 'id',
    'join_table' => 'gi_products_gi_line_items_1_c',
    'join_key_lhs' => 'gi_products_gi_line_items_1gi_products_ida',
    'join_key_rhs' => 'gi_products_gi_line_items_1gi_line_items_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'gi_discounts_gi_products_1' => 
  array (
    'id' => '6409169d-c7ad-bd63-3193-55d560838ead',
    'relationship_name' => 'gi_discounts_gi_products_1',
    'lhs_module' => 'GI_Discounts',
    'lhs_table' => 'gi_discounts',
    'lhs_key' => 'id',
    'rhs_module' => 'GI_Products',
    'rhs_table' => 'gi_products',
    'rhs_key' => 'id',
    'join_table' => 'gi_discounts_gi_products_1_c',
    'join_key_lhs' => 'gi_discounts_gi_products_1gi_discounts_ida',
    'join_key_rhs' => 'gi_discounts_gi_products_1gi_products_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'gi_line_items_change_requests_gi_products_1' => 
  array (
    'id' => '681a9c19-a323-851a-84b5-55d5602db3cc',
    'relationship_name' => 'gi_line_items_change_requests_gi_products_1',
    'lhs_module' => 'GI_Line_Items_Change_Requests',
    'lhs_table' => 'gi_line_items_change_requests',
    'lhs_key' => 'id',
    'rhs_module' => 'GI_Products',
    'rhs_table' => 'gi_products',
    'rhs_key' => 'id',
    'join_table' => 'gi_line_items_change_requests_gi_products_1_c',
    'join_key_lhs' => 'gi_line_itcd35equests_ida',
    'join_key_rhs' => 'gi_line_items_change_requests_gi_products_1gi_products_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'gi_products_catalog_gi_products_1' => 
  array (
    'id' => '696d22b1-e95f-fa31-b198-55d56065afc3',
    'relationship_name' => 'gi_products_catalog_gi_products_1',
    'lhs_module' => 'GI_Products_Catalog',
    'lhs_table' => 'gi_products_catalog',
    'lhs_key' => 'id',
    'rhs_module' => 'GI_Products',
    'rhs_table' => 'gi_products',
    'rhs_key' => 'id',
    'join_table' => 'gi_products_catalog_gi_products_1_c',
    'join_key_lhs' => 'gi_products_catalog_gi_products_1gi_products_catalog_ida',
    'join_key_rhs' => 'gi_products_catalog_gi_products_1gi_products_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'gi_products_campaigns_1' => 
  array (
    'id' => '69a53b8d-0588-3b7e-1931-55d5607d580f',
    'relationship_name' => 'gi_products_campaigns_1',
    'lhs_module' => 'GI_Products',
    'lhs_table' => 'gi_products',
    'lhs_key' => 'id',
    'rhs_module' => 'Campaigns',
    'rhs_table' => 'campaigns',
    'rhs_key' => 'id',
    'join_table' => 'gi_products_campaigns_1_c',
    'join_key_lhs' => 'gi_products_campaigns_1gi_products_ida',
    'join_key_rhs' => 'gi_products_campaigns_1campaigns_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'gi_exam_results_gi_products_1' => 
  array (
    'id' => '6a0e27d8-80be-c6e5-563a-55d5602f1e10',
    'relationship_name' => 'gi_exam_results_gi_products_1',
    'lhs_module' => 'GI_Exam_Results',
    'lhs_table' => 'gi_exam_results',
    'lhs_key' => 'id',
    'rhs_module' => 'GI_Products',
    'rhs_table' => 'gi_products',
    'rhs_key' => 'id',
    'join_table' => 'gi_exam_results_gi_products_1_c',
    'join_key_lhs' => 'gi_exam_results_gi_products_1gi_exam_results_ida',
    'join_key_rhs' => 'gi_exam_results_gi_products_1gi_products_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'gi_locations_gi_products_1' => 
  array (
    'id' => '6a6d3e1b-628a-0f4f-1fcd-55d5606ab276',
    'relationship_name' => 'gi_locations_gi_products_1',
    'lhs_module' => 'GI_Locations',
    'lhs_table' => 'gi_locations',
    'lhs_key' => 'id',
    'rhs_module' => 'GI_Products',
    'rhs_table' => 'gi_products',
    'rhs_key' => 'id',
    'join_table' => 'gi_locations_gi_products_1_c',
    'join_key_lhs' => 'gi_locations_gi_products_1gi_locations_ida',
    'join_key_rhs' => 'gi_locations_gi_products_1gi_products_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'gi_products_meetings_1' => 
  array (
    'id' => '6aa10c14-4d46-9e88-2266-55d56007d8de',
    'relationship_name' => 'gi_products_meetings_1',
    'lhs_module' => 'GI_Products',
    'lhs_table' => 'gi_products',
    'lhs_key' => 'id',
    'rhs_module' => 'Meetings',
    'rhs_table' => 'meetings',
    'rhs_key' => 'id',
    'join_table' => 'gi_products_meetings_1_c',
    'join_key_lhs' => 'gi_products_meetings_1gi_products_ida',
    'join_key_rhs' => 'gi_products_meetings_1meetings_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'gi_products_gi_elearning_courses_1' => 
  array (
    'rhs_label' => 'eLearning Courses',
    'lhs_label' => 'Products',
    'lhs_subpanel' => 'default',
    'rhs_subpanel' => 'default',
    'lhs_module' => 'GI_Products',
    'rhs_module' => 'GI_eLearning_Courses',
    'relationship_type' => 'many-to-many',
    'readonly' => false,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
    'relationship_name' => 'gi_products_gi_elearning_courses_1',
  ),
);