<?php 
 $GLOBALS["dictionary"]["GI_Line_Items"]=array (
  'table' => 'gi_line_items',
  'audited' => true,
  'duplicate_merge' => true,
  'fields' => 
  array (
    'id' => 
    array (
      'name' => 'id',
      'vname' => 'LBL_ID',
      'type' => 'id',
      'required' => true,
      'reportable' => true,
      'comment' => 'Unique identifier',
      'inline_edit' => false,
    ),
    'name' => 
    array (
      'name' => 'name',
      'vname' => 'LBL_NAME',
      'type' => 'name',
      'link' => true,
      'dbType' => 'varchar',
      'len' => 255,
      'unified_search' => false,
      'full_text_search' => 
      array (
        'boost' => 3,
      ),
      'required' => false,
      'importable' => 'false',
      'duplicate_merge' => 'disabled',
      'merge_filter' => 'disabled',
      'duplicate_merge_dom_value' => '0',
    ),
    'date_entered' => 
    array (
      'name' => 'date_entered',
      'vname' => 'LBL_DATE_ENTERED',
      'type' => 'datetime',
      'group' => 'created_by_name',
      'comment' => 'Date record created',
      'enable_range_search' => true,
      'options' => 'date_range_search_dom',
      'inline_edit' => false,
    ),
    'date_modified' => 
    array (
      'name' => 'date_modified',
      'vname' => 'LBL_DATE_MODIFIED',
      'type' => 'datetime',
      'group' => 'modified_by_name',
      'comment' => 'Date record last modified',
      'enable_range_search' => true,
      'options' => 'date_range_search_dom',
      'inline_edit' => false,
    ),
    'modified_user_id' => 
    array (
      'name' => 'modified_user_id',
      'rname' => 'user_name',
      'id_name' => 'modified_user_id',
      'vname' => 'LBL_MODIFIED',
      'type' => 'assigned_user_name',
      'table' => 'users',
      'isnull' => 'false',
      'group' => 'modified_by_name',
      'dbType' => 'id',
      'reportable' => true,
      'comment' => 'User who last modified record',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'modified_by_name' => 
    array (
      'name' => 'modified_by_name',
      'vname' => 'LBL_MODIFIED_NAME',
      'type' => 'relate',
      'reportable' => false,
      'source' => 'non-db',
      'rname' => 'user_name',
      'table' => 'users',
      'id_name' => 'modified_user_id',
      'module' => 'Users',
      'link' => 'modified_user_link',
      'duplicate_merge' => 'disabled',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'created_by' => 
    array (
      'name' => 'created_by',
      'rname' => 'user_name',
      'id_name' => 'modified_user_id',
      'vname' => 'LBL_CREATED',
      'type' => 'assigned_user_name',
      'table' => 'users',
      'isnull' => 'false',
      'dbType' => 'id',
      'group' => 'created_by_name',
      'comment' => 'User who created record',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'created_by_name' => 
    array (
      'name' => 'created_by_name',
      'vname' => 'LBL_CREATED',
      'type' => 'relate',
      'reportable' => false,
      'link' => 'created_by_link',
      'rname' => 'user_name',
      'source' => 'non-db',
      'table' => 'users',
      'id_name' => 'created_by',
      'module' => 'Users',
      'duplicate_merge' => 'disabled',
      'importable' => 'false',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'description' => 
    array (
      'name' => 'description',
      'vname' => 'LBL_DESCRIPTION',
      'type' => 'text',
      'comment' => 'Full text of the note',
      'rows' => 6,
      'cols' => '50',
      'comments' => 'Full text of the note',
      'merge_filter' => 'disabled',
    ),
    'deleted' => 
    array (
      'name' => 'deleted',
      'vname' => 'LBL_DELETED',
      'type' => 'bool',
      'default' => '0',
      'reportable' => false,
      'comment' => 'Record deletion indicator',
    ),
    'created_by_link' => 
    array (
      'name' => 'created_by_link',
      'type' => 'link',
      'relationship' => 'gi_line_items_created_by',
      'vname' => 'LBL_CREATED_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
    ),
    'modified_user_link' => 
    array (
      'name' => 'modified_user_link',
      'type' => 'link',
      'relationship' => 'gi_line_items_modified_user',
      'vname' => 'LBL_MODIFIED_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
    ),
    'assigned_user_id' => 
    array (
      'name' => 'assigned_user_id',
      'rname' => 'user_name',
      'id_name' => 'assigned_user_id',
      'vname' => 'LBL_ASSIGNED_TO_ID',
      'group' => 'assigned_user_name',
      'type' => 'relate',
      'table' => 'users',
      'module' => 'Users',
      'reportable' => true,
      'isnull' => 'false',
      'dbType' => 'id',
      'audited' => true,
      'comment' => 'User ID assigned to record',
      'duplicate_merge' => 'disabled',
    ),
    'assigned_user_name' => 
    array (
      'name' => 'assigned_user_name',
      'link' => 'assigned_user_link',
      'vname' => 'LBL_ASSIGNED_TO_NAME',
      'rname' => 'user_name',
      'type' => 'relate',
      'reportable' => false,
      'source' => 'non-db',
      'table' => 'users',
      'id_name' => 'assigned_user_id',
      'module' => 'Users',
      'duplicate_merge' => 'disabled',
    ),
    'assigned_user_link' => 
    array (
      'name' => 'assigned_user_link',
      'type' => 'link',
      'relationship' => 'gi_line_items_assigned_user',
      'vname' => 'LBL_ASSIGNED_TO_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
      'duplicate_merge' => 'enabled',
      'rname' => 'user_name',
      'id_name' => 'assigned_user_id',
      'table' => 'users',
    ),
    'quantity' => 
    array (
      'required' => true,
      'name' => 'quantity',
      'vname' => 'LBL_QUANTITY',
      'type' => 'int',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'enable_range_search' => false,
      'disable_num_format' => '',
      'min' => false,
      'max' => false,
      'default' => '1',
    ),
    'unit_price' => 
    array (
      'required' => true,
      'name' => 'unit_price',
      'vname' => 'LBL_UNIT_PRICE',
      'type' => 'currency',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 26,
      'size' => '20',
      'enable_range_search' => '1',
      'precision' => 6,
      'default' => 0,
      'inline_edit' => true,
      'options' => 'numeric_range_search_dom',
    ),
    'currency_id' => 
    array (
      'required' => false,
      'name' => 'currency_id',
      'vname' => 'LBL_CURRENCY',
      'type' => 'currency_id',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 36,
      'size' => '20',
      'dbType' => 'id',
      'studio' => 'visible',
      'function' => 
      array (
        'name' => 'getCurrencyDropDown',
        'returns' => 'html',
      ),
    ),
    'total_price' => 
    array (
      'required' => false,
      'name' => 'total_price',
      'vname' => 'LBL_TOTAL_PRICE',
      'type' => 'currency',
      'massupdate' => 0,
      'default' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 26,
      'size' => '20',
      'enable_range_search' => false,
      'precision' => 6,
    ),
    'discount_rate' => 
    array (
      'required' => false,
      'name' => 'discount_rate',
      'vname' => 'LBL_DISCOUNT_RATE',
      'type' => 'varchar',
      'massupdate' => 0,
      'default' => '0',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
    ),
    'total_discount' => 
    array (
      'required' => false,
      'name' => 'total_discount',
      'vname' => 'LBL_TOTAL_DISCOUNT',
      'type' => 'currency',
      'massupdate' => 0,
      'default' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 26,
      'size' => '20',
      'enable_range_search' => false,
      'precision' => 6,
    ),
    'total_price_net' => 
    array (
      'required' => false,
      'name' => 'total_price_net',
      'vname' => 'LBL_TOTAL_PRICE_NET',
      'type' => 'currency',
      'massupdate' => 0,
      'default' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 26,
      'size' => '20',
      'enable_range_search' => false,
      'precision' => 6,
    ),
    'contacts_gi_line_items_1' => 
    array (
      'name' => 'contacts_gi_line_items_1',
      'type' => 'link',
      'relationship' => 'contacts_gi_line_items_1',
      'source' => 'non-db',
      'module' => 'Contacts',
      'bean_name' => 'Contact',
      'vname' => 'LBL_CONTACTS_GI_LINE_ITEMS_1_FROM_CONTACTS_TITLE',
      'id_name' => 'contacts_gi_line_items_1contacts_ida',
    ),
    'contacts_gi_line_items_1_name' => 
    array (
      'name' => 'contacts_gi_line_items_1_name',
      'type' => 'relate',
      'source' => 'non-db',
      'vname' => 'LBL_CONTACTS_GI_LINE_ITEMS_1_FROM_CONTACTS_TITLE',
      'save' => true,
      'id_name' => 'contacts_gi_line_items_1contacts_ida',
      'link' => 'contacts_gi_line_items_1',
      'table' => 'contacts',
      'module' => 'Contacts',
      'rname' => 'name',
      'db_concat_fields' => 
      array (
        0 => 'first_name',
        1 => 'last_name',
      ),
    ),
    'contacts_gi_line_items_1contacts_ida' => 
    array (
      'name' => 'contacts_gi_line_items_1contacts_ida',
      'type' => 'link',
      'relationship' => 'contacts_gi_line_items_1',
      'source' => 'non-db',
      'reportable' => false,
      'side' => 'right',
      'vname' => 'LBL_CONTACTS_GI_LINE_ITEMS_1_FROM_GI_LINE_ITEMS_TITLE',
    ),
    'gi_discounts_gi_line_items_1' => 
    array (
      'name' => 'gi_discounts_gi_line_items_1',
      'type' => 'link',
      'relationship' => 'gi_discounts_gi_line_items_1',
      'source' => 'non-db',
      'module' => 'GI_Discounts',
      'bean_name' => 'GI_Discounts',
      'vname' => 'LBL_GI_DISCOUNTS_GI_LINE_ITEMS_1_FROM_GI_DISCOUNTS_TITLE',
      'id_name' => 'gi_discounts_gi_line_items_1gi_discounts_ida',
    ),
    'gi_discounts_gi_line_items_1_name' => 
    array (
      'name' => 'gi_discounts_gi_line_items_1_name',
      'type' => 'relate',
      'source' => 'non-db',
      'vname' => 'LBL_GI_DISCOUNTS_GI_LINE_ITEMS_1_FROM_GI_DISCOUNTS_TITLE',
      'save' => true,
      'id_name' => 'gi_discounts_gi_line_items_1gi_discounts_ida',
      'link' => 'gi_discounts_gi_line_items_1',
      'table' => 'gi_discounts',
      'module' => 'GI_Discounts',
      'rname' => 'name',
    ),
    'gi_discounts_gi_line_items_1gi_discounts_ida' => 
    array (
      'name' => 'gi_discounts_gi_line_items_1gi_discounts_ida',
      'type' => 'link',
      'relationship' => 'gi_discounts_gi_line_items_1',
      'source' => 'non-db',
      'reportable' => false,
      'side' => 'right',
      'vname' => 'LBL_GI_DISCOUNTS_GI_LINE_ITEMS_1_FROM_GI_LINE_ITEMS_TITLE',
    ),
    'gi_products_gi_line_items_1' => 
    array (
      'name' => 'gi_products_gi_line_items_1',
      'type' => 'link',
      'relationship' => 'gi_products_gi_line_items_1',
      'source' => 'non-db',
      'module' => 'GI_Products',
      'bean_name' => 'GI_Products',
      'vname' => 'LBL_GI_PRODUCTS_GI_LINE_ITEMS_1_FROM_GI_PRODUCTS_TITLE',
      'id_name' => 'gi_products_gi_line_items_1gi_products_ida',
    ),
    'gi_products_gi_line_items_1_name' => 
    array (
      'name' => 'gi_products_gi_line_items_1_name',
      'type' => 'relate',
      'source' => 'non-db',
      'vname' => 'LBL_GI_PRODUCTS_GI_LINE_ITEMS_1_FROM_GI_PRODUCTS_TITLE',
      'save' => true,
      'id_name' => 'gi_products_gi_line_items_1gi_products_ida',
      'link' => 'gi_products_gi_line_items_1',
      'table' => 'gi_products',
      'module' => 'GI_Products',
      'rname' => 'name',
    ),
    'gi_products_gi_line_items_1gi_products_ida' => 
    array (
      'name' => 'gi_products_gi_line_items_1gi_products_ida',
      'type' => 'link',
      'relationship' => 'gi_products_gi_line_items_1',
      'source' => 'non-db',
      'reportable' => false,
      'side' => 'right',
      'vname' => 'LBL_GI_PRODUCTS_GI_LINE_ITEMS_1_FROM_GI_LINE_ITEMS_TITLE',
    ),
    'opportunities_gi_line_items_1' => 
    array (
      'name' => 'opportunities_gi_line_items_1',
      'type' => 'link',
      'relationship' => 'opportunities_gi_line_items_1',
      'source' => 'non-db',
      'module' => 'Opportunities',
      'bean_name' => 'Opportunity',
      'vname' => 'LBL_OPPORTUNITIES_GI_LINE_ITEMS_1_FROM_OPPORTUNITIES_TITLE',
      'id_name' => 'opportunities_gi_line_items_1opportunities_ida',
    ),
    'opportunities_gi_line_items_1_name' => 
    array (
      'name' => 'opportunities_gi_line_items_1_name',
      'type' => 'relate',
      'source' => 'non-db',
      'vname' => 'LBL_OPPORTUNITIES_GI_LINE_ITEMS_1_FROM_OPPORTUNITIES_TITLE',
      'save' => true,
      'id_name' => 'opportunities_gi_line_items_1opportunities_ida',
      'link' => 'opportunities_gi_line_items_1',
      'table' => 'opportunities',
      'module' => 'Opportunities',
      'rname' => 'name',
    ),
    'opportunities_gi_line_items_1opportunities_ida' => 
    array (
      'name' => 'opportunities_gi_line_items_1opportunities_ida',
      'type' => 'link',
      'relationship' => 'opportunities_gi_line_items_1',
      'source' => 'non-db',
      'reportable' => false,
      'side' => 'right',
      'vname' => 'LBL_OPPORTUNITIES_GI_LINE_ITEMS_1_FROM_GI_LINE_ITEMS_TITLE',
    ),
    'prospectlists_gi_line_items_1' => 
    array (
      'name' => 'prospectlists_gi_line_items_1',
      'type' => 'link',
      'relationship' => 'prospectlists_gi_line_items_1',
      'source' => 'non-db',
      'module' => 'ProspectLists',
      'bean_name' => 'ProspectList',
      'vname' => 'LBL_PROSPECTLISTS_GI_LINE_ITEMS_1_FROM_PROSPECTLISTS_TITLE',
      'id_name' => 'prospectlists_gi_line_items_1prospectlists_ida',
    ),
    'prospectlists_gi_line_items_1_name' => 
    array (
      'name' => 'prospectlists_gi_line_items_1_name',
      'type' => 'relate',
      'source' => 'non-db',
      'vname' => 'LBL_PROSPECTLISTS_GI_LINE_ITEMS_1_FROM_PROSPECTLISTS_TITLE',
      'save' => true,
      'id_name' => 'prospectlists_gi_line_items_1prospectlists_ida',
      'link' => 'prospectlists_gi_line_items_1',
      'table' => 'prospect_lists',
      'module' => 'ProspectLists',
      'rname' => 'name',
    ),
    'prospectlists_gi_line_items_1prospectlists_ida' => 
    array (
      'name' => 'prospectlists_gi_line_items_1prospectlists_ida',
      'type' => 'link',
      'relationship' => 'prospectlists_gi_line_items_1',
      'source' => 'non-db',
      'reportable' => false,
      'side' => 'right',
      'vname' => 'LBL_PROSPECTLISTS_GI_LINE_ITEMS_1_FROM_GI_LINE_ITEMS_TITLE',
    ),
    'create_followup_task_c' => 
    array (
      'labelValue' => 'Create a New Follow-up Task',
      'massupdate' => true,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'create_followup_task_c',
      'vname' => 'LBL_CREATE_FOLLOWUP_TASK',
      'type' => 'bool',
      'default' => '0',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'GI_Line_Itemscreate_followup_task_c',
      'custom_module' => 'GI_Line_Items',
    ),
    'date_delivered_c' => 
    array (
      'options' => 'date_range_search_dom',
      'labelValue' => 'Date Delivered',
      'enable_range_search' => '1',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'date_delivered_c',
      'vname' => 'LBL_DATE_DELIVERED',
      'type' => 'date',
      'massupdate' => '1',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'id' => 'GI_Line_Itemsdate_delivered_c',
      'custom_module' => 'GI_Line_Items',
    ),
    'date_shipped_c' => 
    array (
      'options' => 'date_range_search_dom',
      'labelValue' => 'Date Shipped',
      'enable_range_search' => '1',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'date_shipped_c',
      'vname' => 'LBL_DATE_SHIPPED',
      'type' => 'date',
      'massupdate' => '1',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'id' => 'GI_Line_Itemsdate_shipped_c',
      'custom_module' => 'GI_Line_Items',
    ),
    'date_sync_with_moodle_c' => 
    array (
      'labelValue' => 'Date Sync with Moodle',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'date_sync_with_moodle_c',
      'vname' => 'LBL_DATE_SYNC_WITH_MOODLE',
      'type' => 'datetimecombo',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'enable_range_search' => false,
      'dbType' => 'datetime',
      'id' => 'GI_Line_Itemsdate_sync_with_moodle_c',
      'custom_module' => 'GI_Line_Items',
    ),
    'delivery_mode_c' => 
    array (
      'labelValue' => 'Preferred Delivery Mode',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'delivery_mode_c',
      'vname' => 'LBL_DELIVERY_MODE',
      'type' => 'enum',
      'massupdate' => '1',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'delivery_mode_list',
      'studio' => 'visible',
      'dependency' => NULL,
      'id' => 'GI_Line_Itemsdelivery_mode_c',
      'custom_module' => 'GI_Line_Items',
    ),
    'discount_ratio_c' => 
    array (
      'labelValue' => 'Discount Ratio',
      'required' => true,
      'source' => 'custom_fields',
      'name' => 'discount_ratio_c',
      'vname' => 'LBL_DISCOUNT_RATIO',
      'type' => 'decimal',
      'massupdate' => '0',
      'default' => '0.00',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '18',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => '2',
      'id' => 'GI_Line_Itemsdiscount_ratio_c',
      'custom_module' => 'GI_Line_Items',
    ),
    'discount_type_c' => 
    array (
      'labelValue' => 'Discount Type',
      'required' => true,
      'source' => 'custom_fields',
      'name' => 'discount_type_c',
      'vname' => 'LBL_DISCOUNT_TYPE',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => 'Amount',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'discount_type_list',
      'studio' => 'visible',
      'dependency' => NULL,
      'id' => 'GI_Line_Itemsdiscount_type_c',
      'custom_module' => 'GI_Line_Items',
    ),
    'exam_result_c' => 
    array (
      'labelValue' => 'Exam Result',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'exam_result_c',
      'vname' => 'LBL_EXAM_RESULT',
      'type' => 'enum',
      'massupdate' => '1',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'exam_result_list',
      'studio' => 'visible',
      'dependency' => NULL,
      'id' => 'GI_Line_Itemsexam_result_c',
      'custom_module' => 'GI_Line_Items',
    ),
    'excluded_from_invoice_c' => 
    array (
      'labelValue' => 'Excluded From Invoice',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'excluded_from_invoice_c',
      'vname' => 'LBL_EXCLUDED_FROM_INVOICE',
      'type' => 'bool',
      'massupdate' => '0',
      'default' => '0',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'GI_Line_Itemsexcluded_from_invoice_c',
      'custom_module' => 'GI_Line_Items',
    ),
    'moodle_cohort_id_c' => 
    array (
      'labelValue' => 'Moodle Cohort ID',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'moodle_cohort_id_c',
      'vname' => 'LBL_MOODLE_COHORT_ID',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'GI_Line_Itemsmoodle_cohort_id_c',
      'custom_module' => 'GI_Line_Items',
    ),
    'moodle_user_id_c' => 
    array (
      'labelValue' => 'Moodle User ID',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'moodle_user_id_c',
      'vname' => 'LBL_MOODLE_USER_ID',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'GI_Line_Itemsmoodle_user_id_c',
      'custom_module' => 'GI_Line_Items',
    ),
    'provisional_c' => 
    array (
      'labelValue' => 'Provisional',
      'massupdate' => true,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'provisional_c',
      'vname' => 'LBL_PROVISIONAL',
      'type' => 'bool',
      'default' => '0',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'GI_Line_Itemsprovisional_c',
      'custom_module' => 'GI_Line_Items',
    ),
    'reference_c' => 
    array (
      'labelValue' => 'Reference',
      'autoinc_next' => '1',
      'auto_increment' => true,
      'required' => true,
      'source' => 'custom_fields',
      'name' => 'reference_c',
      'vname' => 'LBL_REFERENCE',
      'type' => 'int',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'enable_range_search' => false,
      'disable_num_format' => '1',
      'min' => false,
      'max' => false,
      'id' => 'GI_Line_Itemsreference_c',
      'custom_module' => 'GI_Line_Items',
    ),
    'shipment_details_c' => 
    array (
      'labelValue' => 'Shipment Details / Airway Bill No',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'shipment_details_c',
      'vname' => 'LBL_SHIPMENT_DETAILS',
      'type' => 'text',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'studio' => 'visible',
      'rows' => '4',
      'cols' => '50',
      'id' => 'GI_Line_Itemsshipment_details_c',
      'custom_module' => 'GI_Line_Items',
    ),
    'status_c' => 
    array (
      'labelValue' => 'Status',
      'required' => true,
      'source' => 'custom_fields',
      'name' => 'status_c',
      'vname' => 'LBL_STATUS',
      'type' => 'enum',
      'massupdate' => '1',
      'default' => 'Interested_Cold',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'line_item_status_list',
      'studio' => 'visible',
      'dependency' => NULL,
      'id' => 'GI_Line_Itemsstatus_c',
      'custom_module' => 'GI_Line_Items',
    ),
    'total_before_vat_c' => 
    array (
      'inline_edit' => '',
      'labelValue' => 'Total Before VAT',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'total_before_vat_c',
      'vname' => 'LBL_TOTAL_BEFORE_VAT',
      'type' => 'currency',
      'massupdate' => '0',
      'default' => '0',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '26',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => 6,
      'id' => 'GI_Line_Itemstotal_before_vat_c',
      'custom_module' => 'GI_Line_Items',
    ),
    'vat_amount_c' => 
    array (
      'inline_edit' => '',
      'labelValue' => 'VAT Amount',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'vat_amount_c',
      'vname' => 'LBL_VAT_AMOUNT',
      'type' => 'currency',
      'massupdate' => '0',
      'default' => '0',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '26',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => 6,
      'id' => 'GI_Line_Itemsvat_amount_c',
      'custom_module' => 'GI_Line_Items',
    ),
    'vat_c' => 
    array (
      'inline_edit' => '',
      'labelValue' => 'VAT %',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'vat_c',
      'vname' => 'LBL_VAT',
      'type' => 'decimal',
      'massupdate' => '0',
      'default' => '0.00',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '7',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => '2',
      'id' => 'GI_Line_Itemsvat_c',
      'custom_module' => 'GI_Line_Items',
    ),
  ),
  'relationships' => 
  array (
    'gi_line_items_modified_user' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'GI_Line_Items',
      'rhs_table' => 'gi_line_items',
      'rhs_key' => 'modified_user_id',
      'relationship_type' => 'one-to-many',
    ),
    'gi_line_items_created_by' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'GI_Line_Items',
      'rhs_table' => 'gi_line_items',
      'rhs_key' => 'created_by',
      'relationship_type' => 'one-to-many',
    ),
    'gi_line_items_assigned_user' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'GI_Line_Items',
      'rhs_table' => 'gi_line_items',
      'rhs_key' => 'assigned_user_id',
      'relationship_type' => 'one-to-many',
    ),
  ),
  'optimistic_locking' => true,
  'unified_search' => true,
  'indices' => 
  array (
    'id' => 
    array (
      'name' => 'gi_line_itemspk',
      'type' => 'primary',
      'fields' => 
      array (
        0 => 'id',
      ),
    ),
  ),
  'templates' => 
  array (
    'assignable' => 'assignable',
    'basic' => 'basic',
  ),
  'custom_fields' => true,
);